import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";



const Home: NextPage = () => {
    return (
        <div className="home">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">
                <div className="img-float-left">
                    <Image
                        src="/manuel.svg"
                        alt="youtube-logo"
                        width={350}
                        height={350}
                    />
                </div>
                <div className="text-float-right">
                    <h1>Manuel Casares Gestal</h1>
                    <h3>
                        Concert Pianist & Teacher <br/>Master - Academy of Music<br/>
                        “Krzysztof Penderecki” in Krakow, Poland
                    </h3>
                </div>
            </main>
        </div>
    );
};

export default Home;
