import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
    return (
        <div className="home">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="main">
                <h1>Here will be your page</h1>
            </main>

            <footer className="footer">
                <a
                    href="https://www.gabrielcmoris.com"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className="logo">
                        <Image
                            src="/bust.svg"
                            alt="GabrielCMoris-logo"
                            width={25}
                            height={30}
                        />
                    </span>{" "}
                All rights reserved © 2021
                </a>
            </footer>
        </div>
    );
};

export default Home;
